### ISSUE TITLE
Heat Pump Only Mode Not Working

### ISSUE THREAD

**Issue by prussell69** [bspranger/Hubitat_RheemEcoNet#1]
I've installed the App & Device Handler (Last Updated : 01-05-2019) on my system. I have a Rheem Hybrid Water Heater - Gen 4. I can change the temperature setting up & down, I can change the mode to "Off", or "Energy Saver", but when I choose "Rqst:Heat Pump", nothing happens at the unit (mode doesn't change". I prefer to run in heat pump only mode but can't seem to get that mode to work. I'm basically looking for a way to turn the unit on/off without powering the whole unit.
Any help is much appreciated.

**Comment by bspranger** [comment]
Change the mode on the water heater, then in the device handler turn on debug.

Go to the log then refresh the device and see what the mode name is in the log.

**Comment by prussell69** [comment]
I changed the mode on the WH to "Heat Pump Only", and Smartthings reported: "mode:Heat Pump". When I changed it back to "Energy Saver Mode", it reported: "mode:Energy Saver".
Do you think the device handler is sending "mode:Heat Pump Only" instead of "mode:Heat Pump", and that's the problem?

**Comment by bspranger** [comment]
Yes that is probably the problem.  If you look in the DH for those strings you will probably find them, the change them and see if it works.

**Comment by prussell69** [comment]
I removed the "Only" portion from everywhere in the DH. That did the trick!!
Thank you so much for all your help.
